### PR TITLE
fixed #10 Allow user to see output on Enter

### LINKED ISSUE #10: [FEAT] Allow user to see output on "Enter"
Currently, the user has to tap the "Reverse" button to see the output (Reversed text). It would be great if it was made so that, when the user presses the "Enter" key on their keyboard after typing the text, the output will automatically show up.

Currently, if you try pressing enter, it just refreshes the page.

### PR DESCRIPTION
**Pull request by brandonbyr4**
Fixes #10 

Pressing Enter, or clicking the buttons now correctly displays the output.

### CODE REVIEW

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
The functionality works perfectly. Although, you got rid of the "COPY" button and made that a "SUBMIT" button as well.

**Comment by brandonbyr4** [comment]
Oh no problem I can fix that.  I was not sure what the original functionality was intended to be.  Should the "copy" button copy the original word, or the reversed word to the clipboard.

**Comment by KendallDoesCoding** [comment]
> Oh no problem I can fix that. I was not sure what the original functionality was intended to be. Should the "copy" button copy the original word, or the reversed word to the clipboard.

It copies the reversed text once it is reversed, if you try copying without reversing the text it copies:  . Although, I will create a issue to make it so that,  if text isn't reversed to not copy anything.

**Comment by KendallDoesCoding** [comment]
> > Oh no problem I can fix that. I was not sure what the original functionality was intended to be. Should the "copy" button copy the original word, or the reversed word to the clipboard.
> 
> It copies the reversed text once it is reversed, if you try copying without reversing the text it copies: . Although, I will create a issue to make it so that, if text isn't reversed to not copy anything.

#13

**Pull request closed without merging**
