### PR TITLE
style: add style to the project

### LINKED ISSUE #2: Improve design/interface
The website looks kinda ugly rn, the design requires to be changed to look nice and believable, because this is a real product and people can actually win the prizes mentioned, no scam :)

### PR DESCRIPTION
**Pull request by zabihhaqqani**
fixes #2 

- It improves the design of the project.

### CODE REVIEW

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
Looks perfect but can you add like a solid or gradient background?, if not then no worries will go to merge.

**Comment by zabihhaqqani** [comment]
Sure I will try some backgrounds.

Any color in mind ?

**Comment by KendallDoesCoding** [comment]
Thanks.

**Comment by zabihhaqqani** [comment]
- Before
Capture
- After


If this is fine do I create another pull request or commit to the same pull request?

**Comment by KendallDoesCoding** [comment]
> * Before
>   Capture
> * After
>   
> 
> If this is fine do I create another pull request or commit to the same pull request?

Hi,

I'm not too big of a fan of this gradient.

Can you please use either:
- background: linear-gradient(90deg, #00C9FF 0%, #92FE9D 100%);
or
- background: linear-gradient(90deg, #9ebd13 0%, #008552 100%);

Please change the gradient to the above requested and give me a screenshot, and will tell you which one to go ahead with.

Please commit it in this PR itself.

Thanks & Sorry for the inconvience,
KendallDoesCoding

**Comment by zabihhaqqani** [comment]
Sure will do that

**Comment by KendallDoesCoding** [comment]
Thanks!

**Comment by zabihhaqqani** [comment]
- used this gradient

- background: linear-gradient(90deg, #9ebd13 0%, #008552 100%);

**Comment by KendallDoesCoding** [comment]
Looks much better, but can you change the 2nd line color to look good with
the background, maybe red will work?

**Comment by KendallDoesCoding** [comment]
Nah, doesn't look good, maybe a light colour, you have a look locally and
see what looks good. Dark colours look bad with this background.

**Comment by zabihhaqqani** [comment]
Okay will try

**Comment by KendallDoesCoding** [comment]
Thank you, sorry for the inconvenience.

**Comment by zabihhaqqani** [comment]
1. 
final 2
2.
final

**Comment by zabihhaqqani** [comment]
which one is better?

**Comment by HamzaYehia** [comment]
> which one is better?

I think the first is better

**Comment by KendallDoesCoding** [comment]
> which one is better?

Email replies are giving too many issues, I replied 4 hours ago saying the following, but it didn't show up here:

**2 looks good, please commit these changes to this PR.**

**Comment by zabihhaqqani** [comment]
Sure no problem I will do the changes.

**Comment by zabihhaqqani** [comment]
I have made the commit to the same pull request.

all the changes are done!

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
Thanks a lot for your contribution @zabihhaqqani!

**Comment by zabihhaqqani** [comment]
Thanks for accepting my pull request 😊

**Comment by KendallDoesCoding** [comment]
2 looks good, please commit these changes to this PR.

**Pull request merged**
